version: "3.7"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-08-13T21-54-44Z
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    expose:
      - "9000"
      - "9001"
    environment:
     MINIO_ROOT_USER: &s3_key minio
     MINIO_ROOT_PASSWORD: &s3_secret changeme
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres-14:
    image: benzine/postgres:14
    build:
      context: .
      target: postgres
      args:
        PGSQL_VERSION: 14
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: changeme
      S3_ENDPOINT: http://minio:9000/
      S3_API_KEY: *s3_key
      S3_API_SECRET: *s3_secret
    ports:
      - "127.0.0.127:5432:5432"
    depends_on:
      - minio