name: Build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - postgres-14
          - postgres-13
          - postgres-12
          - postgres-11
          - postgres-10
          - mariadb-10-9
          - mariadb-10-8
          - mariadb-10-7
          - mariadb-10-6
          - mariadb-10-5
          - mariadb-10-4
          - mariadb-10-3
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/login-action@v1
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Bake
        uses: docker/bake-action@v2.1.0
        with:
          files: bake.hcl
          push: true
          targets: ${{ matrix.target }}
